Feat/transactions
kinhosz/Wallet-API pull request #18
Opened 2024-11-03 17:55 UTC by laysearaujo

2024-11-04 17:04 UTC, kinhosz requested changes
Tá muito bom aqui na API, apenas alguns pequenos ajustes. Lembrar, que pra criação de rotas, é importante duas coisas:

1. Criar testes para todas as rotas criadas
2. Popular a conta `admin` no `seeds.rb`

2024-11-05 19:32 UTC, kinhosz requested changes

2024-11-05 19:32 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
> +    params.permit(:date)
nao precisa desse

2024-11-05 19:32 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
> +    end
```rb
transactions = transactions.where(occurred_at: date)
```

2024-11-05 19:32 UTC, kinhosz commented on test/controllers/finance/transactions_controller_test.rb
> +    end
remover comentarios (nao os de nome da rota)
identar o segundo teste

2024-11-06 21:31 UTC, kinhosz requested changes
lembra de rodar `rails test` ou `rails t` localmente, para ter certeza que os testes tao passando.

2024-11-06 21:31 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
> -  end
```rb
def index_by_date_params
    params.require(:date)
end
```

2024-11-06 21:31 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
>      date = permitted_params[:date]
```rb
date = index_by_date_params[:date]
```

2024-11-21 22:04 UTC, laysearaujo commented
Fechando esse PR e criando outro sobre as transações como foi acordado.

2024-11-23 16:26 UTC, kinhosz requested changes
corrige isso aí e a gente mergea.

2024-11-23 16:26 UTC, kinhosz commented on test/controllers/finance/transactions_controller_test.rb
> +        }
devolve os espacos daqui.

2024-11-27 20:46 UTC, kinhosz approved these changes
LGTM

2024-11-28 00:33 UTC, merged