feat: index by date range in transactions
kinhosz/Wallet-API pull request #19
Opened 2024-11-28 01:01 UTC by laysearaujo

2024-11-28 09:20 UTC, kinhosz requested changes
muito bom <3

2024-11-28 09:20 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
> +    end
esses parametros sao obrigatorios. entao voce deve usar o require no `date_range_params`

2024-11-28 09:20 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
> +    end
evitar fazer essas validacoes dentro do controller. como se tratam de validacoes dos parametros, fazer isso no `date_range_params`

2024-11-28 09:20 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
> +    end
e provavelmente, tu poderias so usar os dados direto. o `ActiveRecord` iria gerar um erro, caso nao funcionasse. mas como fez, bota no lugar certo

2024-11-28 09:20 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
> +                                        .where(occurred_at: start_date..end_date)
se voce precisa setar o `user_id`, significa que na verdade voce nao precisa. Voce quer as transacoes do usuario atual dentro do range, certo? Ja temos um helper para pegar as transacoes do usuario atual usando o `alias` que voce mesmo setou. Acho que eh `current_user.transactions.where(ocurred_at: start_date..end_date)`

2024-11-28 09:20 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
> +  end
como `start_date` e `end_date` sao obrigatorios, utilize `params.require(...)`, a gente utiliza `params.permit` quando os parametros sao opcionais

2024-11-28 20:52 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
> +                                        .where(occurred_at: start_date..end_date)
agora que eu percebi, tu não tá passando o `currency`. Este método está retornando todas as transações. Corrige isso também

2024-11-29 01:41 UTC, laysearaujo commented
nas transações também nãoo temos o `currency` acha válido colocar aqui?

2024-11-29 09:59 UTC, kinhosz requested changes

2024-11-29 09:59 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
> +    transactions = Finance::Transaction.where(user_id: current_user.id, occurred_at: date)
```rb
transactions = current_user.finance_transactions(
    index_by_date_params[:currency]
).where(
    occurred_at: index_by_date_params[:date]
)
```

2024-11-29 09:59 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
> +    end
tu ta fazendo duas idas ao banco de dados. Ir ao banco de dados eh a parte mais custosa de uma consulta.

Tu pode fazer isso:

```rb
transactions = current_user.finance_transactions(
    date_range_params[:currency]
).where(
    occured_at: date_range_params[:start_date]..date_range_params[:end_date]
)
```

O ActiveRecord vai agrupar essa informacao e fazer uma so query SQL, indo uma vez ao banco de dados.
Usar `current_user.finance_transactions` no lugar de `Finance::Transactions.where(current_user: user.id)`.
o `finance_transactions` aceita um `currency`, e retorna todas as transactions dessa moeda.

2024-11-29 09:59 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
> +  end
todos aqui precisam do `currency`. Tu deve colocar o `currency` no `require` tambem.
Alias, acho que a gente pode so ignorar o tratamento desse erro. Se a data for invalida, o ActiveRecord vai retornar o erro (nao tenho muita certeza, mas acredito que sim).

2024-11-29 09:59 UTC, kinhosz commented on test/controllers/finance/transactions_controller_test.rb
> +        @transaction_in_range = transaction_in_range
a gente nao precisa ficar usando o `@`. Ele eh utilizado para ser uma variavel global dentro do objeto. Nesse caso, a gente nao precisa necessariamente disso. Mas pode deixar passar esses aq

2024-12-02 11:10 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
>    end
```rb
def index_by_date_params
    params.require(:currency, :date)
end
```

2024-12-02 11:11 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
>      }
```rb
def date_range_params
    params.require(:currency, :start_date, :end_date)
end
```

2024-12-02 23:50 UTC, laysearaujo commented on app/controllers/finance/transactions_controller.rb
>      }
O método `params.require` do Rails não aceita múltiplos argumentos de uma vez. Ele foi projetado para verificar apenas um parâmetro obrigatório por vez, garantindo que esse parâmetro esteja presente e não seja vazio.
Se a gente tentar passar múltiplos argumentos, o Rails lançará um erro do tipo ArgumentError: wrong number of arguments.

2024-12-04 09:24 UTC, kinhosz requested changes

2024-12-04 09:24 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
> +      currency: date_range_params[:currency],
`user_id`

2024-12-04 09:24 UTC, kinhosz commented on app/controllers/finance/transactions_controller.rb
> +      )
`user_id`

2024-12-05 19:08 UTC, kinhosz approved these changes
LGTM

2024-12-10 20:15 UTC, merged